# Generated by Django 2.1 on 2018-08-31 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilDisposalTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_time_field_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('at_time_field_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('at_time_soil_disposal_site_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('at_time_soil_disposal_site_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('image_path', models.TextField()),
                ('mileage', models.DecimalField(decimal_places=0, max_digits=8)),
                ('co2_emissions', models.DecimalField(decimal_places=3, max_digits=13)),
                ('arrived_to_site_flg', models.BooleanField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'soil_disposal_tasks',
            },
        ),
    ]
